export const AUTOCOMPLETE_SOURCE_TYPE_NAMES = new Set(["boolean", "bool", "u8", "i8", "u16", "i16", "u32", "i32", "fixed", "ufixed", "fixed32", "fp5", "float"]);

export function isAutocompleteSourceTypeName(type) {
  return AUTOCOMPLETE_SOURCE_TYPE_NAMES.has(String(type || "").trim().toLowerCase());
}

const AMY_AUTOCOMPLETE_LEGACY_BLOCKLIST = new Set([
  "label MainLoop",
  "MainLoop:",
  "on Choice gosub Init, Update, Draw",
  "initialize mode 2 text color with $F0",
  "read joypad 1 into Pad1",
  "read vdp status into Status",
  "if button 1 on Pad1 goto FirePressed",
  "if button 1 on Pad1 then goto FirePressed",
  "dim u16 Score = 0",
  "dim u8 Counter = 0",
  "dim bool Visible = true",
  "multiply Counter by 3",
  "mul Counter by 3",
  "divide Counter by 3",
  "div Counter by 3",
  "for I = 7 downto 0",
  "for I = 10 downto 0 step 2",
  "ram bool GameOver = false",
  "ram bcd 2 Score",
  "ram bcd 3 Score",
  "put chars TitleLine at 8,8 count 9",
  "put tile $41 at 8,8",
  "print \"HELLO\" at 8,8",
  "read frame into FrameCount",
  "read spinner 1 into SpinX",
  "read spinner 2 into SpinY",
  "endif",
  "end do",
  "end for",
  "wend",
  "default",
  "case default",
  "plot 10,10 color 15",
  "sqrt 144 into Root",
  "add Counter32 by Addend32",
  "sub Counter32 by Addend32",
  "copy array Backup from Board",
  "copy array Backup from Board count 8"
]);

const AMY_AUTOCOMPLETE_V21_ADDITIONS = [
  ["' Comment", "Preferred AMY comment form on its own line or after code"],
  ["rem Comment", "Alternative BASIC-style comment form on its own line or after code"],
  ["if joypad(1).left then", "Preferred inline input branch for movement"],
  ["if joypad(1).button1 then", "Preferred inline input branch for fire/actions"],
  ["if joypad(1).left then PlayerX -= 1", "Short inline movement branch"],
  ["if joypad(1).right then PlayerX += 1", "Short inline movement branch"],
  ["Pad1 = joypad(1)", "Read the raw decoded joypad byte as an expression"],
  ["Key = keypad(1)", "Read the decoded keypad byte as an expression"],
  ["project \"My Game\"", "Studio project name only — does not affect the compiled ROM title or BIOS screen"],
  ["cartridge \"MY GAME/AMY/1986\"", "Activate ColecoVision BIOS title screen metadata — format: \"TITLE/COMPANY/YEAR\""],
  ["cartridge \"MAPPY {tm}/NAMCO/1984\"", "Coleco BIOS title-screen metadata with {tm} or {c} escapes — format: \"TITLE/COMPANY/YEAR\""],
  ["Status = vdp.status", "Read the VDP status byte as an expression"],
  ["SpinX = spinner(1)", "Read spinner delta 1 as a signed byte expression"],
  ["SpinY = spinner(2)", "Read spinner delta 2 as a signed byte expression"],
  ["FrameCount = frame", "Read the 16-bit Amy frame counter as an expression"],
  ["print at 0,0, \"VDP=\", vdp.status", "Print mixed text and inline expressions on one HUD line"],
  ["print at HudX, HudY, \"SCORE:\", Score", "Preferred compact HUD print form"],
  ["print at 5,Y, str$(Value)", "Print a formatted numeric text expression directly at screen coordinates"],
  ["print at 5,Y, str$(Score, digits 5)", "Print a zero-padded numeric text field"],
  ["print at 5,Y, str$(Score, width 5)", "Print a right-aligned numeric text field using the configured pad tile"],
  ["print at 5,Y, \"A:\" + str$(A)", "Print a lightweight concatenated text expression without a manual buffer"],
  ["Buffer = str$(Value)", "Preferred lightweight text-buffer assignment for formatted numeric text"],
  ["Buffer = digits$(Score, 5)", "Write a zero-padded numeric text field into a u8 buffer"],
  ["Buffer = width$(Score, 5)", "Write a right-aligned numeric text field into a u8 buffer"],
  ["Line = \"A:\" + str$(A)", "Preferred lightweight text-buffer assignment using literals plus str$"],
  ["A = sqrt(B)", "Preferred expression form for square root assignment"],
  ["A = abs(B)", "Preferred expression form for absolute value assignment"],
  ["S = sgn(Value)", "Preferred expression form for sign extraction"],
  ["I = int(Value)", "Preferred expression form for integerization"],
  ["L = log(Value)", "Preferred expression form for fp5 logarithm"],
  ["E = exp(Value)", "Preferred expression form for fp5 exponentiation"],
  ["if Lives = 0 then print \"FAIL\" at 10,10 else print \"PASS\" at 10,10", "Single-line if/else"],
  ["Upper = highword Counter32", "Extract the upper 16 bits of a u32/i32 value"],
  ["Lower = lowword Counter32", "Extract the lower 16 bits of a u32/i32 value"],
  ["Counter32 = Seed32", "Copy one 4-byte little-endian integer to another"],
  ["Camera32 = NextCamera32", "Copy one fixed32 value into another"],
  ["Backup = Score", "Copy one scalar or BCD value with canonical assignment"],
  ["define byte as u8", "Create a project-local source alias for a canonical type"],
  ["Counter *= 3", "Multiply a u8 or u16 variable in-place"],
  ["Counter /= 3", "Divide a u8 variable in-place"],
  ["for I = 7 to 0 step -1", "Count downward with the preferred negative-step form"],
  ["for I = 10 to 0 step -2", "Count downward by two with the preferred negative-step form"],
  ["fixed32 Camera32 = 1.5", "Declare a signed 16.16 fixed-point value with a decimal literal"],
  ["fixed32 Velocity32 = -0.125", "Declare a signed 16.16 fixed-point value with a negative decimal literal"],
  ["Camera32 += Velocity32", "Add one fixed32 value into another"],
  ["Camera32 -= 0.25", "Subtract a fixed32 decimal literal"]
];

const AMY_AUTOCOMPLETE_DETAIL_OVERRIDES = new Map([
  ["sub run_demo:", "Define a named subroutine"],
  ["function AddTwo(u16 a, u16 b) as u16", "Define a function that returns a 16-bit value"],
  ["elseif Lives = 0 then", "Else-if branch inside an if block"],
  ["else if Lives = 0 then", "Else-if branch inside an if block (spaced alias)"],
  ["else", "Fallback branch inside an if block"],
  ["end if", "Close an if block"],
  ["do", "Start a loop block"],
  ["do while Counter < 10", "Pre-test loop"],
  ["do until Ready", "Pre-test until loop"],
  ["loop while Counter < 10", "Post-test loop"],
  ["loop until Ready", "Post-test until loop"],
  ["select case Choice", "Start a multi-branch selection block"],
  ["sub DrawSprite(u8 X, u8 Y, u8 Pattern)", "Define a subroutine with typed parameters"],
  ["local u16 Score = 0", "Declare a local 16-bit runtime variable"],
  ["local i16 Delta = 0", "Declare a local signed 16-bit integer"],
  ["local bool Done = false", "Declare a local boolean"],
  ["sub RunDemo:", "Start a subroutine block"],
  ["MyRoutine", "Call a no-argument subroutine without CALL"],
]);

export const AMY_AUTOCOMPLETE = [
  ["screen off", "Turn display and NMI off together"],
  ["screen on", "Turn display and NMI on together"],
  ["screen off no nmi", "Explicitly turn display off without enabling interrupts"],
  ["screen on no nmi", "Turn display on while keeping NMI disabled"],
  ["nmi off", "Disable VBlank interrupts"],
  ["nmi on", "Enable VBlank interrupts"],
  ["display off", "Advanced: toggle only the display bit and keep NMI state unchanged"],
  ["display on", "Advanced: toggle only the display bit and keep NMI state unchanged"],
  ["text screen", "Standard 32x24 ColecoVision text bootstrap with ASCII font, 32 color groups, and cls"],
  ["tile screen", "Advanced Graphics II tile/text bootstrap with duplicated pattern and color thirds"],
  ["bitmap screen", "Set up the drawable bitmap screen used by pset, line, and circle; default color is $F0"],
  ["bitmap screen color $F0", "Set up the drawable bitmap screen with an explicit full color-table byte"],
  ["picture screen", "Set up the raw Graphics II picture/table screen for uploading pattern and color assets"],
  ["multicolor screen", "Set up TMS9918A Mode 3 multicolor and leave the display blanked until screen on"],
  ["set default name table vram $1800", "Select the active name table base"],
  ["set sprite pattern table vram.pattern", "Point sprite patterns at the text/pattern table base"],
  ["load default ascii", "Upload BIOS ASCII font"],
  ["load default ascii bold", "Upload BIOS ASCII font using legacy bold styling"],
  ["load default ascii italic", "Upload BIOS ASCII font using legacy italic styling"],
  ["load default ascii bold italic", "Upload BIOS ASCII font using legacy bold+italic styling"],
  ["duplicate mode 2 text patterns", "Copy first pattern third to the other two"],
  ["fill mode 2 text color with $F0", "Fill all Mode 2 text color thirds"],
  ["cls", "Clear the current screen surface (name table in text modes, pattern bytes in multicolor)"],
  ["print at 8,8, \"HELLO\"", "Print one or more items starting at one position"],
  ["print at 1,1, \"HP:\", Hp", "Print mixed text and typed values on one HUD line"],
  ["print \"HELLO\" at 8,8", "Print a zero-terminated string"],
  ["print FrameCount at 8,8 width 5", "Print a numeric value right-aligned with pad tiles instead of leading zeroes"],
  ["put char $41 at 8,8", "Write one tile/character"],
  ["put chars TitleLine at 8,8 count 9", "Write a fixed-length char table"],
  ["put Border count 2 at 0,10", "Preferred row-write surface for a fixed-length u8 table"],
  ["put FrameBuf at 6,20", "Write a full known-length u8 buffer or data row; count is inferred"],
  ["put FrameBuf centered at 20", "Write a known-length u8 buffer or data row centered on one text row"],
  ["put Buffer frame size 8,8 at 0,0", "Write a rectangular tile frame from a u8 buffer"],
  ["put MazeMap frame size 32,19 at 0,0", "Write a rectangular tile frame from a data chars map"],
  ["data MazeMap chars", "Start a ROM character-map data block using quoted text rows"],
  ["\"#  {CoinTile}  #\"", "Inside data chars, insert a custom tile byte using a constant escape"],
  ["fill at 0,10 $2D count 8", "Fill a horizontal run in the name table with one repeated tile"],
  ["set text colors light green on dark blue count 32", "Fill text color table entries using Coleco color names instead of raw color bytes"],
  ["set text colors light green count 32", "Fill text color table entries with transparent background"],
  ["set text colors cyan on dark blue at 6 count 2", "Fill part of the text color table using foreground/background color names"],
  ["set text colors cyan at 6 count 2", "Fill part of the text color table with transparent background"],
  ["Tile = get char at 8,8", "Read one tile/character as an assignment expression"],
  ["RowBuffer = get count 8 at 0,10", "Read a horizontal name-table run into a u8 buffer"],
  ["FrameBuffer = get frame size 8,8 at 0,0", "Read a rectangular tile frame into a u8 buffer"],
  ["vpoke vram.name + $0000, $41", "Write one u8 value directly to VRAM"],
  ["vpeek vram.name + $0000 into Value", "Read one u8 value directly from VRAM"],
  ["read vram vram.name count 64 into Buffer", "Read a VRAM block into a u8 array"],
  ["merge PatternBytes count 8 to vram.pattern mask $F0 xor $0F", "Copy bytes to VRAM as (source & mask) xor value"],
  ["pset 10,10", "Set one pixel in graphics mode1"],
  ["pset 10,10 color 15", "Set one pixel and force its row color nibble in graphics mode1"],
  ["pset multicolor 2,2 color 5", "Set one Mode 3 multicolor pixel nibble"],
  ["PixelColor = pget multicolor 2,2", "Read one Mode 3 multicolor pixel nibble"],
  ["preset 10,10", "Clear one pixel in graphics mode1"],
  ["line 20,20 to 220,170", "Draw a clipped line in graphics mode1"],
  ["line 20,20 to 220,170 color 15", "Draw a clipped colored line in graphics mode1"],
  ["circle 80,100 radius 20", "Draw a clipped circle in graphics mode1"],
  ["circle 80,100 radius 20 color 15", "Draw a clipped colored circle in graphics mode1"],
  ["fill row 12 from 0 count 32 with $2D", "Fill a horizontal run"],
  ["wait", "Wait one frame / VBlank"],
  ["wait 5 frames", "Wait N frames / VBlanks"],
  ["label MainLoop", "Define a jump target"],
  ["MainLoop:", "Plain label shorthand"],
  ["goto MainLoop", "Jump to a label"],
  ["on Choice goto Title, Game, Credits", "Branch to the 1-based target selected by an int8/int16 expression"],
  ["on Choice gosub Init, Update, Draw", "Call the 1-based target selected by an int8/int16 expression"],
  ["sub run_demo:", "Define a named subroutine"],
  ["function AddTwo(u16 a, u16 b) as u16", "Define a function that returns a 16-bit value"],
  ["function NextMove as u8", "Define a function with no parameters"],
  ["function IsReady as bool", "Define a function that returns a boolean"],
  ["Score = AddTwo(3, 4)", "Assign the result of a function call"],
  ["return", "Return from a subroutine"],
  ["return Value", "Return a value from a function"],
  ["exit sub", "Leave the current procedure immediately (alias)"],
  ["if Score > 10 then", "Start a structured if block"],
  ["elseif Lives = 0 then", "Else-if branch inside an if block"],
  ["else if Lives = 0 then", "Else-if branch inside an if block (spaced alias)"],
  ["else", "Fallback branch inside an if block"],
  ["end if", "Close an if block"],
  ["do", "Start a loop block"],
  ["do while Counter < 10", "Pre-test loop"],
  ["do until Ready", "Pre-test until loop"],
  ["loop", "Close a do block and repeat forever"],
  ["loop while Counter < 10", "Post-test loop"],
  ["loop until Ready", "Post-test until loop"],
  ["continue do", "Skip to the next iteration of the innermost do/loop block"],
  ["exit do", "Leave the innermost do/loop block immediately"],
  ["for I = 0 to 31", "Structured counting loop"],
  ["for I = 8 to 0 step -2", "Counted loop using a negative step to move downward naturally"],
  ["next", "Close a for loop"],
  ["continue for", "Skip to the next iteration of the innermost for/next block"],
  ["exit for", "Leave the innermost for/next block immediately"],
  ["while Counter < 10", "Structured conditional loop"],
  ["continue while", "Skip to the next iteration of the innermost while/end while block"],
  ["exit while", "Leave the innermost while/end while block immediately"],
  ["end while", "Close a while loop"],
  ["select case Choice", "Start a multi-branch selection block"],
  ["case 1", "Branch body for one select case value"],
  ["case 1 to 3", "Branch body for an inclusive select case range"],
  ["case else", "Fallback branch for select case"],
  ["end select", "Close a select case block"],
  ["read joypad 1 into Pad1", "Hardware read: copy decoded controller state into a u8 variable"],
  ["read vdp status into Status", "Hardware read: copy the BIOS-shadowed VDP status u8 into a RAM variable"],
  ["if any collision goto Hit", "Branch when the VDP sprite coincidence bit is set"],
  ["hitbox PlayerHitbox = 3,5 size 10,9", "Declare a named local sprite hitbox rectangle"],
  ["if sprite 0 hitbox PlayerHitbox collides with sprite 1 hitbox EnemyHitbox goto Hit", "Branch on sprite collision using distinct named hitboxes"],
  ["tile type solid = $23,$24", "Declare a named tile property group for pixel-to-tile gameplay collision"],
  ["if tile under PlayerX + 4,PlayerY + 15 is solid goto OnGround", "Test the tile containing a pixel coordinate"],
  ["if tiles under box PlayerX,PlayerY size 16,16 contain hazard goto Hurt", "Test all tiles touched by a pixel-space box"],
  ["find tile coin under box PlayerX,PlayerY size 16,16 into HitX,HitY", "Find the first matching tile in a pixel-space box; returns tile coordinates or 255,255"],
  ["if button 1 on Pad1 goto FirePressed", "Branch on controller input"],
  ["if button 1 on Pad1 then goto FirePressed", "Branch on controller input (optional then)"],
  ["Tile = random(2) + 16", "Assign an int8 expression using RANDOM(count)"],
  ["Score = 12345", "Canonical Amy assignment"],
  ["set number digits to $30", "Set the tile index for digit '0' (for example $30 = ASCII '0', $00 for a custom charset)"],
  ["set number pad to $20", "Set the tile index used for numeric left-padding (for example $20 = space tile)"],
  ["Copy32 = Counter32", "Copy a typed value with canonical Amy assignment"],
  ["clear Score", "Canonical Amy clear for numeric variables"],
  ["Counter32 += Addend32", "Canonical Amy typed addition"],
  ["Counter32 -= Addend32", "Canonical Amy typed subtraction"],
  ["Counter32 += 1", "Canonical Amy increment-by-formula"],
  ["format Counter32 into Digits", "Canonical Amy typed formatting"],
  ["format FrameCount into Digits width 5", "Format a numeric value using pad tiles instead of leading zeroes"],
  ["print Number at 10,10 digits 2", "Print a typed numeric value"],
  ["set sound table SoundTable", "Install a lib4ksa-style sound table"],
  ["set sound table SoundTable areas 8", "Install a sound table with an explicit area count"],
  ["include \"@project/sounds.inc\"", "Include an ASM/data file verbatim in the generated assembly"],
  ["play song SongTable", "Start a lib4ksa-style music table"],
  ["stop song", "Stop current music-table playback"],
  ["stop all", "Stop music and mute all sound slots"],
  ["play sound 1", "Trigger a sound slot"],
  ["stop sound 1", "Terminate a single sound slot"],
  ["mute all", "Mute active sound slots"],
  ["enable spinner", "Enable roller/spinner interrupt support"],
  ["disable spinner", "Disable roller/spinner interrupt support"],
  ["reset spinner 1", "Clear spinner delta 1"],
  ["reset spinner 2", "Clear spinner delta 2"],
  ["reset spinners", "Clear both spinner deltas"],
  ["u8 Counter = 0, Limit = 10", "Declare one or more same-type variables; top-level becomes global, inside a sub/function it becomes local"],
  ["u8 Stars[32]", "Declare a global u8 array at top level"],
  ["record Piece:", "Define a named record type; this is the canonical Amy spelling"],
  ["end record", "Close a record definition"],
  ["Piece Items[8]", "Declare a global array of record values once Piece is defined"],
  ["set Items[0].X = 12", "Write one field inside a record or array-of-record element"],
  ["u16 Score = 0, HighScore = 0", "Declare 16-bit score variables on one line"],
  ["bcd digits 5 Credits, Bonus", "Declare same-width packed BCD score variables by displayed digit count"],
  ["bool GameOver = false, Ready = true", "Declare packed boolean flags on one line"],
  ["local u16 Score = 0", "Declare a local 16-bit runtime variable"],
  ["local i16 Delta = 0", "Declare a local signed 16-bit integer"],
  ["sub RunDemo:", "Start a subroutine block"],
  ["local bool Done = false", "Declare a local boolean"],
  ["data Lookup bytes 1,2,3,4", "Declare ROM bytes on one line"],
  ["data Lookup bytes = 1,2,3,4", "Declare ROM bytes on one line with explicit assignment style"],
  ["data Charset bytes", "Start a multiline ROM u8 block"],
  ["data Smile sprite16", "Start a visual 16x16 sprite bitmap block"],
  ["define sprites Smile at 0", "Upload sprite16 data to vram.spr_pat and select the sprite pattern table"],
  ["bitmap \"......XXXX......\"", "Append one visual bitmap row to a bitmap-enabled data block"],
  ["restore Lookup", "Reset DATA reading to a ROM data block"],
  ["read Value", "DATA cursor: read the next item from the active ROM data block into a variable"],
  ["read X, Y, Tile", "DATA cursor: read several items from the active ROM data block in sequence"],
  ["copy Charset to vram.pattern", "Copy a ROM/RAM byte block to VRAM"],
  ["copy Charset + Offset count 8 to vram.pattern + 128", "Copy a byte slice from a ROM/RAM table to a VRAM offset"],
  ["copy vram.name to Buffer count 64", "Read back a VRAM block into a byte array buffer"],
  ["replace solid with EmptyTile in FrameBuf frame size 3,3", "Replace tile values or tile types inside a RAM frame buffer"],
  ["replace coin with EmptyTile in FrameBuf frame size 5,5 into CoinsFound", "Replace tiles in a RAM frame buffer and store the replacement count"],
  ["merge PatternBytes count 8 to vram.pattern mask $F0 xor $0F", "Copy bytes to VRAM while applying lib4ksa-style AND/XOR masks"],
  ["define chars Charset at 27", "Upload one or more 8-byte characters across all Mode 2 pattern thirds"],
  ["define colors CharsetColors at 27", "Upload one or more 8-byte color rows across all Mode 2 color thirds"],
  ["reflect pattern 0 to 16 count 1 vertical", "Reflect pattern-table entries around the vertical axis"],
  ["reflect pattern 16 to 17 count 1 horizontal", "Reflect pattern-table entries around the horizontal axis"],
  ["rotate pattern 17 to 18 count 1 90", "Rotate pattern-table entries 90 degrees clockwise"],
  ["copy TextLine1 to vram.name + $00C8", "Copy a text/data block to a VRAM offset"],
  ["decompress mdkrle Pattern to vram.pattern", "Decompress a supported asset/table directly into VRAM"],
  ["decompress rle Pattern to vram.pattern", "Alias for lib4ksa/getput11 mdkrle-style VRAM decompression"],
  ["show picture TitleScreen", "All-in-one bitmap picture display: set mode, upload data, then screen on"],
  ["upload picture TitleScreen", "Upload/decompress a grouped picture without changing screen state"],
  ["set screen pages vram.name and vram $1C00", "Set viewed/edit name tables for double buffering"],
  ["swap screens", "Swap viewed and edit name tables"],
  ["wipe screen up", "Blank name table rows bottom-to-top, one row per frame"],
  ["wipe screen down", "Blank name table rows top-to-bottom, one row per frame"],
  ["wipe bitmap up", "Clear bitmap color rows bottom-to-top, one pixel row per frame"],
  ["wipe bitmap down", "Clear bitmap color rows top-to-bottom, one pixel row per frame"],
  ["play dsound SpeechData", "Play 4-bit PCM digital sound (blocking, silences PSG music)"],
  ["play dsound SpeechData step 0", "Play 4-bit PCM digital sound with explicit quality step (0=highest)"],
  ["sprites 8x8", "Use 8x8 sprite size"],
  ["sprites 16x16", "Use 16x16 sprite size"],
  ["sprites simple", "Zoom off — render sprites at native pixel size"],
  ["sprites double", "Zoom on — render sprites at 2x pixel size"],
  ["set sprite count 4", "Set the active sprite shadow count"],
  ["set sprite 0 to 64,80,1,15", "Write one native sprite shadow entry"],
  ["set sprite 0 tile PlayerX,PlayerY pattern PlayerPattern color 15", "Place a sprite from tile coordinates (X,Y), applying X*8 and Y*8-1"],
  ["set sprite 0 tile PlayerX,PlayerY pattern PlayerPattern color 15 offset -4,-8", "Place a sprite from tile coordinates with a signed pixel offset/anchor adjustment"],
  ["set sprite 0 pattern to PlayerPattern", "Change only the pattern byte in a sprite shadow entry"],
  ["set sprite 0 pattern bit 1 on", "Set one bit in a sprite pattern byte, useful for animation variants"],
  ["set sprite 0 pattern bit 1 off", "Clear one bit in a sprite pattern byte"],
  ["toggle sprite 0 pattern bit 0", "Toggle one bit in a sprite pattern byte"],
  ["move sprite 0 toward tile PlayerX,PlayerY step 4 wait 3 frames animate pattern xor 1", "Smoothly move a sprite shadow entry toward tile coordinates, updating sprites each step"],
  ["hide sprite 0", "Hide one native sprite shadow entry"],
  ["clear sprites", "Clear the native sprite shadow table"],
  ["update sprites", "Upload the native sprite shadow table to VRAM"],
  ["pause until press", "Wait for fire release, then wait for a new fire press on joypad 1"],
  ["pause until press on joypad 1", "Wait for fire release, then wait for a new fire press on a specific joypad"],
  ["wait 180 frames or press", "Wait up to N frames, but stop early if fire is pressed"],
  ["wait 180 frames or press on joypad 1", "Timed wait interruptible by a specific joypad fire button"],
  ["wait key1", "Wait until keypad 1 reports key 1"],
  ["choose keypad 1 to 3 into Speed", "Wait for a keypad choice in range"],
  ["wait key release", "Wait until keypad 1 is released"],
  ["sub MyRoutine", "Define a subroutine label"],
  ["Counter = 10", "Assign a runtime variable"],
  ["fixed Velocity = 0.5", "Declare a signed 8.8 fixed-point value with a decimal literal"],
  ["ufixed ScreenX = 40.75", "Declare an unsigned 8.8 fixed-point value with a decimal literal"],
  ["fixed32 Camera32 = 1.5", "Declare a signed 16.16 fixed-point value with a decimal literal"],
  ["copy Score to Backup", "Copy one scalar or BCD runtime value into another"],
  ["Counter += 1", "Increment a runtime variable"],
  ["Counter -= 1", "Decrement a runtime variable"],
  ["Scale *= 3", "Multiply a u8 or unsigned u16 variable in-place"],
  ["Scale /= 4", "Divide a u8 variable in-place"],
  ["bounce BallX by BallDX between 0 and 31", "Move by signed byte delta and reverse at edges"],
  ["clamp PlayerX between 1 and 30", "Constrain a u8 variable to an inclusive range"],
  ["swap PlayerX with OtherX", "Exchange values of two same-type RAM variables or array elements"],
  ["swap Arr[I] with Arr[J]", "Exchange two int8/int16 array elements (I and J are RAM vars or constants)"],
  ["set bit 0 of Flags", "Set a single bit (0-7) of a u8 variable"],
  ["clear bit 0 of Flags", "Clear a single bit (0-7) of a u8 variable"],
  ["reset bit 0 of Flags", "Clear a single bit (0-7) of a u8 variable (alias)"],
  ["if bit 0 of Flags goto Label", "Branch if a specific bit is set"],
  ["if not bit 0 of Flags goto Label", "Branch if a specific bit is clear"],
  ["min PlayerX with 30", "Keep the smaller value in a u8/u16 variable"],
  ["max PlayerX with 1", "Keep the larger value in a u8/u16 variable"],
  ["clamp Score between 0 and 999", "Constrain a u8/u16 variable to an inclusive range"],
  ["if GameOver goto Label", "Branch if a boolean or non-zero u8 is true"],
  ["if not GameOver goto Label", "Branch if a boolean or non-zero u8 is false"],
  ["toggle GameOver", "Flip a boolean (or u8: 0→1, non-zero→0)"],
  ["sub DrawSprite(u8 X, u8 Y, u8 Pattern)", "Define a subroutine with typed parameters"],
  ["DrawSprite(10, 20, 1)", "Call a subroutine directly with arguments"],
  ["print Score at 10,10 digits 5", "Print decimal u16 value (up to 5 digits, covers 0-65535)"],
  ["print Score at 10,10 digits 3", "Print decimal value in a fixed 3-digit field"],
  ["print i8 Delta at 10,10 digits 4", "Print a signed 8-bit value as [sign][3 digits]"],
  ["print i16 Delta at 10,10 digits 6", "Print a signed 16-bit value as [sign][5 digits]"],
  ["print Counter32 at 10,10", "Print a 4-byte little-endian unsigned integer as 10 digits"],
  ["print Delta32 at 10,10 digits 11", "Print a signed 32-bit value as [sign][10 digits]"],
  ["print Speed at 10,10", "Print a typed numeric value, including fixed as siii.ff and ufixed as iii.ff"],
  ["print hex Speed at 10,10", "Print raw little-endian memory bytes as hex pairs for debugging"],
  ["ufixed Lsb = raw $0001", "Initialize fixed-point storage with exact raw bits instead of value scaling"],
  ["PixelX = floor Position", "Extract the integer byte of a fixed/ufixed value"],
  ["SubPixel = fraction Position", "Extract the fractional byte of a fixed/ufixed value"],
  ["Hi = highbyte Score", "Extract the high byte of a word/integer/fixed value"],
  ["Lo = lowbyte Score", "Extract the low byte of a word/integer/fixed value"],
  ["Upper = highword Counter32", "Extract the upper 16 bits of a u32/i32 value"],
  ["Lower = lowword Counter32", "Extract the lower 16 bits of a u32/i32 value"],
  ["format Score into Digits digits 5", "Format an unsigned 8/16-bit value into a u8 buffer"],
  ["format Counter32 into Digits", "Format a 4-byte little-endian unsigned integer into a 10-byte buffer"],
  ["format Delta32 into Digits digits 11", "Format a signed 32-bit value into a byte buffer"],
  ["format Delta into Digits digits 4", "Format a signed 8-bit value into a byte buffer"],
  ["format Delta16 into Digits digits 6", "Format a signed 16-bit value into a byte buffer"],
  ["format Speed into Digits", "Format a fixed or ufixed 8.8 value into a byte buffer"],
  ["format hex Speed into HexText", "Format raw little-endian memory bytes as hex pairs into a u8 buffer"],
  ["clear Counter32", "Clear a 4-byte little-endian integer"],
  ["Counter32 = Seed32", "Copy one 4-byte little-endian integer to another"],
  ["Counter32 += Addend32", "Add one 4-byte integer to another"],
  ["inc Counter32", "Increment a 4-byte integer"],
  ["Counter32 -= Addend32", "Subtract one 4-byte integer from another"],
  ["shift array SnakeX down 1", "Shift array elements toward higher indices (make room at index 0)"],
  ["shift array SnakeX up 1", "Shift array elements toward lower indices (discard index 0)"],
  ["fill array Board with 0", "Clear a byte array to a constant value (fast LDIR)"],
  ["fill array Tiles repeating Pattern", "Fill a byte array by repeating a source pattern (overlapping LDIR)"],
  ["fill array Tiles repeating Pattern count 32", "Fill first N bytes of array by repeating a source pattern"],
  ["copy Board to Backup", "Bulk-copy one array or byte buffer into another"],
  ["copy Board count 8 to Backup", "Bulk-copy the first N elements/bytes into another array or buffer"],
  ["reverse array Board", "Reverse all elements of a byte array in place"],
  ["reverse array Board from 2 count 6", "Reverse a slice of a byte array in place"],
  ["TileRow <<= 3", "Modern alias for left-shifting a byte or word variable by N bits"],
  ["Score >>= 2", "Modern alias for right-shifting a byte or word variable by N bits"],
  ["bcd digits 5 Credits", "Declare a 5-digit packed BCD value (stored in 3 bytes, printed as 5 digits)"],
  ["bcd digits 8 Score8", "Declare an 8-digit packed BCD score value"],
  ["Score += 100", "Add a decimal value or byte variable to a BCD score"],
  ["Score += Delta", "Add a u8 or i8 variable to a BCD score"],
  ["Score -= 50", "Subtract a decimal value or byte variable from a BCD score (clamps to 0)"],
  ["Score -= Delta", "Subtract a u8 or i8 variable from a BCD score (clamps to 0)"],
  ["clear Score", "Reset a numeric or BCD variable to zero"],
  ["Backup = Score", "Copy one BCD score variable into another of the same size"],
  ["Score = Bonus", "Load a BCD score from a u8 or i8 variable inline without a helper runtime"],
  ["print at 10,2, Score", "Print a BCD score as ASCII decimal digits (tile offset $30)"],
  ["format ScoreBcd into Digits", "Format a BCD score into a byte buffer as ASCII digits"],
  ["print at 10,2, Score tiles $00", "Print a BCD score using a custom tile charset starting at tile 0"]
]
  .map(([snippet, detail]) => ({ snippet, detail }))
  .filter(({ snippet }) => !AMY_AUTOCOMPLETE_LEGACY_BLOCKLIST.has(snippet))
  .concat(AMY_AUTOCOMPLETE_V21_ADDITIONS.map(([snippet, detail]) => ({ snippet, detail })))
  .map((item) => ({
    snippet: item.snippet,
    detail: (AMY_AUTOCOMPLETE_DETAIL_OVERRIDES.get(item.snippet) || item.detail)
      .replace(/QBASIC-style\s+/g, "")
      .replace(/\s*\(QuickBASIC style\)/g, "")
  }));

export function autocompleteCommandBias(snippet) {
  const lower = String(snippet || "").toLowerCase();
  let score = 0;
  if (lower.includes("joypad(") || lower.includes("keypad(") || lower.includes("vdp.status")) score -= 6;
  if (lower.startsWith("print at ")) score -= 5;
  if (/^[a-z_][a-z0-9_]*\s*=\s*(sqrt|sqr|abs|sgn|int|log|exp)\s*\(/.test(lower)) score -= 7;
  if (/^[a-z_][a-z0-9_]*\s*=\s*str\$\s*\(/.test(lower)) score -= 7;
  if (/^[a-z_][a-z0-9_]*\s*=\s*get\s+(char|count|frame)\b/.test(lower)) score -= 7;
  if (/^put\s+[a-z_][a-z0-9_]*\s+count\s+.+\s+at\s+/.test(lower)) score -= 6;
  if (/^put\s+[a-z_][a-z0-9_]*\s+frame\s+size\s+.+\s+at\s+/.test(lower)) score -= 6;
  if (lower.startsWith("copy ") && !lower.startsWith("copy bytes ") && !lower.startsWith("copy bcd ")) score -= 4;
  if (/\bthen\b.+\belse\b/.test(lower)) score -= 4;
  if (/[+\-*/]=/.test(lower)) score -= 4;
  if (/^for\s+\w+\s*=.+\bstep\s+-/.test(lower)) score -= 3;
  if (lower.startsWith("sub ")) score -= 3;
  if (lower.startsWith("function ")) score -= 2;
  if (lower.startsWith("loop forever")) score -= 2;
  if (/\binto\b/.test(lower)) score += 8;
  if (lower.startsWith("put at ")) score += 8;
  if (lower.startsWith("put chars ")) score += 8;
  if (/^(sqrt|sqr|abs|sgn|int|log|exp)\s+.+\s+into\s+/.test(lower)) score += 8;
  if (lower.startsWith("read joypad ") || lower.startsWith("read vdp status")) score += 7;
  if (lower.startsWith("copy bytes ") || lower.startsWith("copy bcd ")) score += 4;
  if (lower.startsWith("label ") || /:$/.test(lower)) score += 10;
  return score;
}
