export function bindStudioShellEvents({
  bindAsmViewEvents,
  bindTopUiEvents,
  bindStudioRuntimeEvents,
  args
}) {
  const {
    els,
    projectState,
    autocompleteState,
    helpers,
    runtime,
    constants
  } = args;

  bindAsmViewEvents({
    els,
    getProject: projectState.getProject,
    getExpandedAsm: runtime.getExpandedAsm,
    setExpandedAsm: runtime.setExpandedAsm,
    getAsmViewMode: runtime.getAsmViewMode,
    setAsmViewMode: runtime.setAsmViewMode,
    syncAsmEditor: helpers.syncAsmEditor,
    expandAsmIncludes: helpers.expandAsmIncludes,
    setStatus: helpers.setStatus
  });

  bindTopUiEvents({
    els,
    normalizeOptimizationLevel: helpers.normalizeOptimizationLevel,
    renderExamplePicker: helpers.renderExamplePicker,
    renderExampleMeta: helpers.renderExampleMeta,
    getExampleById: helpers.getExampleById,
    buildProjectFromExample: helpers.buildProjectFromExample,
    clearCompiledArtifacts: helpers.clearCompiledArtifacts,
    closeTopbarMenu: helpers.closeTopbarMenu,
    closeAutocomplete: helpers.closeAutocomplete,
    updateAutocomplete: helpers.updateAutocomplete,
    syncAutocompleteSelection: helpers.syncAutocompleteSelection,
    applyAutocomplete: helpers.applyAutocomplete,
    getAutocompleteState: autocompleteState.get,
    setAutocompleteState: autocompleteState.set,
    refreshProjectGraph: helpers.refreshProjectGraph,
    refreshSourceCartridgeMeta: helpers.refreshSourceCartridgeMeta,
    saveProjectToStorage: helpers.saveProjectToStorage,
    updateOptimizationHint: helpers.updateOptimizationHint,
    scheduleEditorInsightsRefresh: helpers.scheduleEditorInsightsRefresh,
    syncUiFromProject: helpers.syncUiFromProject,
    setStatus: helpers.setStatus,
    newProject: helpers.newProject,
    getProject: projectState.getProject,
    setProject: projectState.setProject,
    setLastLibResolution: runtime.setLastLibResolution,
    getExpandedAsm: runtime.getExpandedAsm,
    setExpandedAsm: runtime.setExpandedAsm,
    getAsmViewMode: runtime.getAsmViewMode,
    setAsmViewMode: runtime.setAsmViewMode,
    createNewTileSetProjectFiles: helpers.createNewTileSetProjectFiles,
    createNewBitmapProjectFiles: helpers.createNewBitmapProjectFiles,
    setExampleCategoryFilter: runtime.setExampleCategoryFilter,
    setExampleTagFilter: runtime.setExampleTagFilter,
    setExampleSearchFilter: runtime.setExampleSearchFilter
  });

  bindStudioRuntimeEvents({
    els,
    importProjectObject: helpers.importProjectObject,
    clearCompiledArtifacts: helpers.clearCompiledArtifacts,
    syncUiFromProject: helpers.syncUiFromProject,
    closeTopbarMenu: helpers.closeTopbarMenu,
    setStatus: helpers.setStatus,
    getProject: projectState.getProject,
    setProject: projectState.setProject,
    setExpandedAsm: runtime.setExpandedAsm,
    setAsmViewMode: runtime.setAsmViewMode,
    exportProject: helpers.exportProject,
    downloadText: helpers.downloadText,
    transpileSource: helpers.transpileSource,
    STUDIO_SOURCE_LANG: constants.studioSourceLang,
    analyzeLibraryResolution: helpers.analyzeLibraryResolution,
    setLastLibResolution: runtime.setLastLibResolution,
    setSourceCartridgeMeta: runtime.setSourceCartridgeMeta,
    updatePreviewActions: helpers.updatePreviewActions,
    generateAsm: helpers.generateAsm,
    renderLibraryResolution: helpers.renderLibraryResolution,
    saveProjectToStorage: helpers.saveProjectToStorage,
    refreshProjectGraph: helpers.refreshProjectGraph,
    appendCartridgeNormalizationWarning: helpers.appendCartridgeNormalizationWarning,
    getSourceCartridgeMeta: runtime.getSourceCartridgeMeta,
    getExpandedAsm: runtime.getExpandedAsm,
    getAsmViewMode: runtime.getAsmViewMode,
    compileGeneratedAsm: helpers.compileGeneratedAsm,
    getOptimizationProfile: helpers.getOptimizationProfile,
    inspectColecoBinary: helpers.inspectColecoBinary,
    setCompiledOutputs: runtime.setCompiledOutputs,
    syncAsmEditor: helpers.syncAsmEditor,
    updateEmulatorUi: helpers.updateEmulatorUi,
    previewColecoBiosTitleScreen: helpers.previewColecoBiosTitleScreen,
    previewColecoBiosTitleFromMetadata: helpers.previewColecoBiosTitleFromMetadata,
    previewDinaBiosTitleScreen: helpers.previewDinaBiosTitleScreen,
    previewDinaBiosTitleFromMetadata: helpers.previewDinaBiosTitleFromMetadata,
    getCompiledRom: runtime.getCompiledRom,
    runEmbeddedEmulator: helpers.runEmbeddedEmulator,
    setEmulatorBios: runtime.setEmulatorBios,
    resetEmbeddedEmulator: helpers.resetEmbeddedEmulator,
    downloadBinary: helpers.downloadBinary,
    getCompiledMemoryMap: runtime.getCompiledMemoryMap,
    getCompiledSymbols: runtime.getCompiledSymbols,
    getCompiledListing: runtime.getCompiledListing,
    copyText: helpers.copyText,
    openAssembler: helpers.openAssembler,
    cvSampleRate: helpers.cvSampleRate,
    wavToDsound: helpers.wavToDsound,
    audioBufferToDsound: helpers.audioBufferToDsound,
    dsoundBytesToPreviewSamples: helpers.dsoundBytesToPreviewSamples,
    insertTextIntoSource: helpers.insertTextIntoSource,
    ensureProjectFilePathCandidate: helpers.ensureProjectFilePathCandidate,
    upsertProjectFile: helpers.upsertProjectFile,
    bytesToBase64: helpers.bytesToBase64,
    addImportedProjectFiles: helpers.addImportedProjectFiles
  });
}
