import {createGraphicsEditorModal} from "./editorShell.js?v=20260719-graphics-crt-overlay";
import {bitmapPixel,bitmapViewportPoint,copyBitmapSelection,ellipsePixels,expandPixels,floodBitmap,linePixels,paintBitmapPixel,pasteBitmapSelectionSmart,rectanglePixels} from "./graphicsBitmapTools.js?v=20260811-bitmap-zoom-memory";
export async function openBitmapScreenGraphicsEditor(editor,o){
 const {palette,patternFile,colorFile,decodedProjectFileBytes,detectCodecFromName,compressBytes,decompressBytes,bytesToBase64,upsertProjectFile,setStatus}=o;
 if(!patternFile||!colorFile){setStatus("Cannot open "+editor.name+": bitmap-screen requires pattern and color files.");return}
 let pattern=Uint8Array.from(await decodedProjectFileBytes(patternFile)),color=Uint8Array.from(await decodedProjectFileBytes(colorFile));
 if(pattern.length!==6144||color.length!==6144){setStatus("Cannot open "+editor.name+": linear Mode 2 requires 6144 pattern and color bytes.");return}
 let dirty=false,fg=15,bg=1,tool="pen",filled=false,brush=1,grid=false,zoom=1,zoomLeft=0,zoomTop=0,zoomPositions=new Map(),spaceHeld=false,panStart=null,start=null,drawing=false,moving=false,moveOffset=null,pasteUndo=false,pasteDirtyBefore=false,pasteReturnSelection=null,selection=null,clipboard=null,preview=null;const undo=[],redo=[];
 let detachKeys=()=>{};const modal=createGraphicsEditorModal({title:editor.name,className:"graphics-editor-modal--bitmap",onCloseRequest:()=>!dirty||confirm("Close without saving bitmap changes?"),onAfterClose:()=>detachKeys()}),{dialog}=modal;
 const icons={
  pencil:'<path d="M4 20l4-1 11-11-3-3L5 16zM14 7l3 3"/>',line:'<path d="M4 20L20 4"/><circle cx="4" cy="20" r="1"/><circle cx="20" cy="4" r="1"/>',rect:'<rect x="4" y="5" width="16" height="14" rx="1"/>',ellipse:'<ellipse cx="12" cy="12" rx="8" ry="6"/>',bucket:'<path d="M5 11l7-7 7 7-7 7zM8 8l8 8M18 17c0 2 3 2 3 0 0-1.2-1.5-3-1.5-3S18 15.8 18 17z"/>',picker:'<path d="M15 4l5 5-9 9H6v-5zM13 6l5 5M5 20h7"/>',select:'<path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5"/>',paste:'<path d="M9 5h6M9 3h6v4H9z"/><rect x="5" y="5" width="14" height="16" rx="2"/>',copy:'<rect x="8" y="8" width="11" height="11" rx="1"/><path d="M16 8V5H5v11h3"/>',cut:'<circle cx="6" cy="7" r="3"/><circle cx="6" cy="17" r="3"/><path d="M8.5 8.5L20 18M8.5 15.5L20 6"/>',grid:'<rect x="4" y="4" width="16" height="16"/><path d="M9.3 4v16M14.7 4v16M4 9.3h16M4 14.7h16"/>',zoomIn:'<circle cx="10" cy="10" r="6"/><path d="M14.5 14.5L21 21M10 7v6M7 10h6"/>',zoomOut:'<circle cx="10" cy="10" r="6"/><path d="M14.5 14.5L21 21M7 10h6"/>',left:'<path d="M19 12H5M11 6l-6 6 6 6"/>',right:'<path d="M5 12h14M13 6l6 6-6 6"/>',up:'<path d="M12 19V5M6 11l6-6 6 6"/>',down:'<path d="M12 5v14M6 13l6 6 6-6"/>',undo:'<path d="M9 7H4v-5M4 7c3-4 10-5 14-1 4 4 2 11-3 13"/>',redo:'<path d="M15 7h5v-5M20 7c-3-4-10-5-14-1-4 4-2 11 3 13"/>',save:'<path d="M5 3h12l3 3v15H4V3zM8 3v6h8V3M8 21v-7h8v7"/>',filled:'<rect x="5" y="5" width="14" height="14" fill="currentColor" stroke="none"/>'
 };
 const svgIcon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||""}</svg>`;
 const setIcon=(button,name,label)=>{button.innerHTML=svgIcon(name);if(label){button.title=label;button.setAttribute("aria-label",label)}};
 const bar=document.createElement("div");bar.className="graphics-editor-toolbar graphics-bitmap-toolbar";const buttons=new Map();
 for(const [id,label,icon] of [["pen","Pencil (P)","pencil"],["line","Line (L)","line"],["rect","Rectangle (R)","rect"],["ellipse","Ellipse (O)","ellipse"],["fill","Fill (B)","bucket"],["picker","Pipette (Alt+click)","picker"],["select","Select (S)","select"],["paste","Paste (Ctrl+V)","paste"]]){const b=document.createElement("button");setIcon(b,icon,label);b.onclick=()=>{tool=id;preview=null;controls();render()};buttons.set(id,b);bar.append(b)}
 const fillLabel=document.createElement("label"),fillCheck=document.createElement("input");fillCheck.type="checkbox";fillCheck.onchange=()=>{filled=fillCheck.checked;render()};fillLabel.title="Filled shapes (F)";fillLabel.className="graphics-editor-toggle";const fillGlyph=document.createElement("span");fillGlyph.innerHTML=svgIcon("filled");fillLabel.append(fillCheck,fillGlyph);const brushSelect=document.createElement("select");brushSelect.className="graphics-bitmap-brush";brushSelect.title="Brush / outline size in pixels";brushSelect.setAttribute("aria-label","Brush / outline size");for(const size of [1,2,3,4,6,8]){const option=document.createElement("option");option.value=size;option.textContent=size+" px";brushSelect.append(option)}brushSelect.onchange=()=>{brush=Number(brushSelect.value)||1;render()};
 const copy=document.createElement("button"),cut=document.createElement("button"),gridButton=document.createElement("button"),zoomOut=document.createElement("button"),zoomIn=document.createElement("button"),panLeft=document.createElement("button"),panUp=document.createElement("button"),panDown=document.createElement("button"),panRight=document.createElement("button"),ub=document.createElement("button"),rb=document.createElement("button"),save=document.createElement("button");setIcon(copy,"copy","Copy selection (Ctrl+C)");setIcon(cut,"cut","Cut selection (Ctrl+X)");setIcon(gridButton,"grid","Toggle 8×8 grid (X)");setIcon(zoomOut,"zoomOut","Zoom out (Shift+Z)");setIcon(zoomIn,"zoomIn","Zoom in (Z)");for(const [button,label,icon]of[[panLeft,"Pan left","left"],[panUp,"Pan up","up"],[panDown,"Pan down","down"],[panRight,"Pan right","right"]]){setIcon(button,icon,label);button.className="graphics-bitmap-pan"}setIcon(ub,"undo","Undo (Ctrl+Z)");setIcon(rb,"redo","Redo (Ctrl+Y)");setIcon(save,"save","Save files");bar.append(fillLabel,brushSelect,copy,cut,gridButton,zoomOut,zoomIn,panLeft,panUp,panDown,panRight,ub,rb,save);dialog.append(bar);
 const body=document.createElement("div");body.className="graphics-bitmap-body";const viewport=document.createElement("div");viewport.className="graphics-bitmap-viewport";const canvas=document.createElement("canvas");canvas.width=256;canvas.height=192;canvas.className="graphics-bitmap-canvas";canvas.tabIndex=0;canvas.oncontextmenu=e=>e.preventDefault();viewport.append(canvas);
 const side=document.createElement("aside");side.className="graphics-bitmap-side";const readout=document.createElement("div"),pal=document.createElement("div");pal.className="graphics-bitmap-palette";
 for(let i=0;i<16;i++){const b=document.createElement("button");b.dataset.color=i;b.title=(i?"Color ":"Transparent ")+"$"+i.toString(16).toUpperCase()+"; left=foreground, right=background";if(i===0)b.className="graphics-editor-color-swatch--transparent";else b.style.background=palette[i];b.onclick=()=>{fg=i;controls()};b.oncontextmenu=e=>{e.preventDefault();bg=i;controls()};pal.append(b)}
 const help=document.createElement("p");help.textContent="Left=FG, right=BG. P/L/R/O/S/B tools · F fill · X grid · Z/Shift+Z zoom · Ctrl+C/X/V/Z/Y · Esc cancel · Space+drag pans zoom.";side.append(readout,pal,help);body.append(viewport,side);dialog.append(body);
 const snap=()=>({p:Uint8Array.from(pattern),c:Uint8Array.from(color),s:selection&&{...selection}}),push=()=>{undo.push(snap());if(undo.length>64)undo.shift();redo.length=0},restore=s=>{pattern.set(s.p);color.set(s.c);selection=s.s;dirty=true;render();controls()};
 function controls(){for(const[id,b]of buttons)b.classList.toggle("active",id===tool);buttons.get("paste").disabled=!clipboard;copy.disabled=!selection;cut.disabled=!selection;gridButton.classList.toggle("active",grid);zoomOut.disabled=zoom===1;zoomIn.disabled=zoom===8;zoomOut.classList.toggle("active",zoom>1);zoomIn.classList.toggle("active",zoom>1);for(const button of[panLeft,panUp,panDown,panRight])button.hidden=zoom===1;ub.disabled=!undo.length;rb.disabled=!redo.length;readout.textContent="FG $"+fg.toString(16).toUpperCase()+" · BG $"+bg.toString(16).toUpperCase()+" · "+brush+" px · "+zoom+"×";for(const b of pal.children){const i=+b.dataset.color;b.classList.toggle("foreground",i===fg);b.classList.toggle("background",i===bg)}}
 function previewPoints(){if(!preview||!start||tool==="select")return[];if(tool==="line")return expandPixels(linePixels(start.x,start.y,preview.x,preview.y),brush);if(tool==="rect")return rectanglePixels(start.x,start.y,preview.x,preview.y,filled,brush);if(tool==="ellipse")return ellipsePixels(start.x,start.y,preview.x,preview.y,filled,brush);return[]}
 function render(){
  let renderPattern=pattern,renderColor=color;const points=previewPoints();
  if(points.length){renderPattern=Uint8Array.from(pattern);renderColor=Uint8Array.from(color);for(const[x,y]of points)paintBitmapPixel(renderPattern,renderColor,x,y,start.col)}
  if(preview&&clipboard&&(tool==="paste"||moving)){if(renderPattern===pattern){renderPattern=Uint8Array.from(pattern);renderColor=Uint8Array.from(color)}pasteBitmapSelectionSmart(renderPattern,renderColor,preview.x,preview.y,clipboard,palette)}
  const c=canvas.getContext("2d"),full=c.createImageData(256,192);
  for(let y=0;y<192;y++)for(let x=0;x<256;x++){const h=palette[bitmapPixel(renderPattern,renderColor,x,y)]||"#000000",m=/^#([0-9a-f]{6})$/i.exec(h),q=(y*256+x)*4;full.data[q]=m?parseInt(m[1].slice(0,2),16):0;full.data[q+1]=m?parseInt(m[1].slice(2,4),16):0;full.data[q+2]=m?parseInt(m[1].slice(4,6),16):0;full.data[q+3]=255}
  let image=full;
  if(zoom>1){image=c.createImageData(256,192);const sourceX=zoomLeft*8,sourceY=zoomTop*8;for(let y=0;y<192;y++){const sy=sourceY+Math.floor(y/zoom);for(let x=0;x<256;x++){const sx=sourceX+Math.floor(x/zoom),to=(y*256+x)*4,from=(sy*256+sx)*4;image.data[to]=full.data[from];image.data[to+1]=full.data[from+1];image.data[to+2]=full.data[from+2];image.data[to+3]=255}}}
  c.putImageData(image,0,0);
  if(grid){const step=8*zoom;c.strokeStyle="rgba(255,255,255,.28)";c.lineWidth=1;c.beginPath();for(let x=step;x<256;x+=step){c.moveTo(x+.5,0);c.lineTo(x+.5,192)}for(let y=step;y<192;y+=step){c.moveTo(0,y+.5);c.lineTo(256,y+.5)}c.stroke()}
  const sx=x=>zoom>1?(x-zoomLeft*8)*zoom:x,sy=y=>zoom>1?(y-zoomTop*8)*zoom:y,scale=zoom;
  if(selection){c.strokeStyle="#fff";c.setLineDash([2,2]);c.strokeRect(sx(selection.x)+.5,sy(selection.y)+.5,selection.width*scale,selection.height*scale);c.setLineDash([])}
  if(preview&&start&&tool==="select"){c.strokeStyle="#65dbef";c.setLineDash([2,2]);c.strokeRect(sx(Math.min(start.x,preview.x))+.5,sy(Math.min(start.y,preview.y))+.5,(Math.abs(preview.x-start.x)+1)*scale,(Math.abs(preview.y-start.y)+1)*scale);c.setLineDash([])}
 }
 const point=e=>{const r=canvas.getBoundingClientRect(),screenX=Math.max(0,Math.min(255,Math.floor((e.clientX-r.left)*256/r.width))),screenY=Math.max(0,Math.min(191,Math.floor((e.clientY-r.top)*192/r.height)));return bitmapViewportPoint(screenX,screenY,zoom,zoomLeft,zoomTop)}; const paint=(pts,col)=>{for(const[x,y]of pts)paintBitmapPixel(pattern,color,x,y,col);dirty=true};
 const contains=(area,p)=>area&&p.x>=area.x&&p.x<area.x+area.width&&p.y>=area.y&&p.y<area.y+area.height;
 const clampPaste=p=>({x:Math.max(0,Math.min(256-clipboard.width,p.x)),y:Math.max(0,Math.min(192-clipboard.height,p.y))});
 const clearArea=area=>{for(let y=area.y;y<area.y+area.height;y+=1)for(let x=area.x;x<area.x+area.width;x+=1)paintBitmapPixel(pattern,color,x,y,bg);dirty=true};
 canvas.onpointerdown=e=>{if(e.button!==0&&e.button!==2)return;canvas.focus();if(spaceHeld&&zoom>1){panStart={clientX:e.clientX,clientY:e.clientY,left:zoomLeft,top:zoomTop};canvas.setPointerCapture?.(e.pointerId);return}const p=point(e),col=e.button===2?bg:fg;if(e.altKey||tool==="picker"){if(e.button===2)bg=bitmapPixel(pattern,color,p.x,p.y);else fg=bitmapPixel(pattern,color,p.x,p.y);controls();return}if(tool==="fill"){push();floodBitmap(pattern,color,p.x,p.y,col);dirty=true;render();controls();return}if(tool==="paste"&&clipboard){push();const at=clampPaste(p);pasteBitmapSelectionSmart(pattern,color,at.x,at.y,clipboard,palette);pasteUndo=false;pasteReturnSelection=null;selection={x:at.x,y:at.y,width:clipboard.width,height:clipboard.height};tool="select";preview=null;dirty=true;render();controls();return}if(tool==="select"&&contains(selection,p)){pasteDirtyBefore=dirty;push();pasteUndo=true;pasteReturnSelection={...selection};clipboard=copyBitmapSelection(pattern,color,selection);moveOffset={x:p.x-selection.x,y:p.y-selection.y};preview={x:selection.x,y:selection.y};clearArea(selection);selection=null;moving=true;drawing=true;canvas.setPointerCapture?.(e.pointerId);render();controls();return}push();start={...p,col};preview=p;drawing=true;canvas.setPointerCapture?.(e.pointerId);if(tool==="pen"){paint(expandPixels([[p.x,p.y]],brush),col);render()}};
 canvas.onpointermove=e=>{if(panStart&&zoom>1){const r=canvas.getBoundingClientRect(),dx=Math.round((panStart.clientX-e.clientX)/(r.width/(32/zoom))),dy=Math.round((panStart.clientY-e.clientY)/(r.height/(24/zoom))),maxX=32-32/zoom,maxY=24-24/zoom;zoomLeft=Math.max(0,Math.min(maxX,panStart.left+dx));zoomTop=Math.max(0,Math.min(maxY,panStart.top+dy));render();return}const p=point(e);if(tool==="paste"&&clipboard&&!drawing){preview=clampPaste(p);render();return}if(!drawing)return;if(moving){preview=clampPaste({x:p.x-moveOffset.x,y:p.y-moveOffset.y});render();return}if(tool==="pen"){const previous=preview||p;paint(expandPixels(linePixels(previous.x,previous.y,p.x,p.y),brush),start.col);preview=p}else preview=p;render()};
 canvas.onpointerup=e=>{if(panStart){panStart=null;canvas.releasePointerCapture?.(e.pointerId);return}if(!drawing)return;const p=point(e);drawing=false;canvas.releasePointerCapture?.(e.pointerId);if(moving){const at=preview||clampPaste({x:p.x-moveOffset.x,y:p.y-moveOffset.y});pasteBitmapSelectionSmart(pattern,color,at.x,at.y,clipboard,palette);pasteUndo=false;pasteReturnSelection=null;selection={x:at.x,y:at.y,width:clipboard.width,height:clipboard.height};moving=false;moveOffset=null;tool="select";start=null;preview=null;dirty=true;render();controls();return}if(!start)return;if(tool==="line")paint(expandPixels(linePixels(start.x,start.y,p.x,p.y),brush),start.col);else if(tool==="rect")paint(rectanglePixels(start.x,start.y,p.x,p.y,filled,brush),start.col);else if(tool==="ellipse")paint(ellipsePixels(start.x,start.y,p.x,p.y,filled,brush),start.col);else if(tool==="select"){selection={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),width:Math.abs(p.x-start.x)+1,height:Math.abs(p.y-start.y)+1};undo.pop()}start=null;preview=null;render();controls()};
 copy.onclick=()=>{if(!selection)return;pasteUndo=false;pasteReturnSelection={...selection};clipboard=copyBitmapSelection(pattern,color,selection);preview={x:selection.x,y:selection.y};selection=null;tool="paste";render();controls()};
 cut.onclick=()=>{if(!selection)return;pasteDirtyBefore=dirty;push();pasteUndo=true;pasteReturnSelection={...selection};clipboard=copyBitmapSelection(pattern,color,selection);preview={x:selection.x,y:selection.y};clearArea(selection);selection=null;tool="paste";render();controls()};
 const cancelPaste=()=>{const mustRestore=moving||pasteUndo;moving=false;drawing=false;moveOffset=null;preview=null;tool="select";pasteUndo=false;if(mustRestore&&undo.length){const previous=undo.pop();pattern.set(previous.p);color.set(previous.c);selection=previous.s;dirty=pasteDirtyBefore}else selection=pasteReturnSelection&&{...pasteReturnSelection};pasteReturnSelection=null;render();controls()};
 dialog.tabIndex=-1;
const chooseTool=id=>{if(buttons.has(id)&&!buttons.get(id).disabled){tool=id;preview=null;controls();render()}};
const pan=(dx,dy)=>{if(zoom===1)return;const maxX=32-32/zoom,maxY=24-24/zoom;zoomLeft=Math.max(0,Math.min(maxX,zoomLeft+dx));zoomTop=Math.max(0,Math.min(maxY,zoomTop+dy));render()};const setZoom=next=>{const previousZoom=zoom,centerX=zoomLeft+16/previousZoom,centerY=zoomTop+12/previousZoom;if(previousZoom>1)zoomPositions.set(previousZoom,{left:zoomLeft,top:zoomTop});zoom=Math.max(1,Math.min(8,next));const remembered=zoomPositions.get(zoom),maxX=32-32/zoom,maxY=24-24/zoom;if(zoom===1){zoomLeft=0;zoomTop=0}else if(remembered){zoomLeft=remembered.left;zoomTop=remembered.top}else{zoomLeft=Math.max(0,Math.min(maxX,centerX-16/zoom));zoomTop=Math.max(0,Math.min(maxY,centerY-12/zoom))}render();controls()};
const handleKeyDown=e=>{if(!dialog.isConnected)return;const key=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;if(e.key===" "){e.preventDefault();spaceHeld=true;canvas.style.cursor=zoom>1?"grab":"crosshair";return}if(e.key==="Escape"){if(moving||tool==="paste")cancelPaste();else if(selection){selection=null;render();controls()}else return;e.preventDefault();e.stopPropagation();return}const tag=e.target?.tagName;if(tag==="INPUT"||tag==="SELECT"||tag==="TEXTAREA")return;if(ctrl&&key==="z"){e.preventDefault();ub.click();return}if(ctrl&&key==="y"){e.preventDefault();rb.click();return}if(ctrl&&key==="c"){e.preventDefault();copy.click();return}if(ctrl&&key==="x"){e.preventDefault();cut.click();return}if(ctrl&&key==="v"){e.preventDefault();if(clipboard)chooseTool("paste");return}if(zoom>1&&e.key.startsWith("Arrow")){e.preventDefault();if(e.key==="ArrowLeft")pan(-1,0);if(e.key==="ArrowRight")pan(1,0);if(e.key==="ArrowUp")pan(0,-1);if(e.key==="ArrowDown")pan(0,1);return}const map={p:"pen",l:"line",r:"rect",o:"ellipse",s:"select",b:"fill"};if(map[key]){e.preventDefault();chooseTool(map[key]);return}if(key==="f"){e.preventDefault();fillCheck.checked=!fillCheck.checked;filled=fillCheck.checked;render();return}if(key==="x"){e.preventDefault();gridButton.click();return}if(key==="z"){e.preventDefault();(e.shiftKey?zoomOut:zoomIn).click()}};
const handleKeyUp=e=>{if(!dialog.isConnected||e.key!==" ")return;spaceHeld=false;panStart=null;canvas.style.cursor=""};
window.addEventListener("keydown",handleKeyDown,true);window.addEventListener("keyup",handleKeyUp,true);detachKeys=()=>{window.removeEventListener("keydown",handleKeyDown,true);window.removeEventListener("keyup",handleKeyUp,true)}; gridButton.onclick=()=>{grid=!grid;render();controls()};
 zoomOut.onclick=()=>setZoom(zoom/2);zoomIn.onclick=()=>setZoom(zoom*2);panLeft.onclick=()=>pan(-1,0);panRight.onclick=()=>pan(1,0);panUp.onclick=()=>pan(0,-1);panDown.onclick=()=>pan(0,1);
 ub.onclick=()=>{if(undo.length){redo.push(snap());restore(undo.pop())}};rb.onclick=()=>{if(redo.length){undo.push(snap());restore(redo.pop())}}; async function write(file,bytes){const codec=String(file.codec||detectCodecFromName(file.path)||"raw").toLowerCase(),encoded=codec==="raw"?bytes:await compressBytes(codec,bytes),check=codec==="raw"?encoded:await decompressBytes(codec,encoded);if(check.length!==bytes.length||check.some((v,i)=>v!==bytes[i]))throw Error("Recompression failed for "+file.path);upsertProjectFile({...file,codec,base64:bytesToBase64(encoded)})}
 save.onclick=async()=>{try{await write(patternFile,pattern);await write(colorFile,color);dirty=false;undo.length=redo.length=0;controls();setStatus("Saved bitmap files for "+editor.name)}catch(e){setStatus(e.message)}};const fitCanvas=()=>{const width=viewport.clientWidth,height=viewport.clientHeight;if(!width||!height)return;const scale=Math.max(1,Math.floor(Math.min(width/256,height/192)));canvas.style.width=256*scale+"px";canvas.style.height=192*scale+"px"};render();controls();modal.mount();new ResizeObserver(fitCanvas).observe(viewport);requestAnimationFrame(fitCanvas);dialog.focus();setStatus("Opened experimental bitmap editor for "+editor.name);
}
