; Generated by tools/build-earth-globe-assets.mjs.

FRAME_00H_MAP:
    db $00,$FF,$FF,$01,$A8,$D5,$A8,$00
    db $FF,$FF,$FF,$E5,$A1,$C9,$F3,$FF
    db $FF,$FF,$FF,$1F,$7F,$81,$FF,$FF
    db $FF,$FF,$FF,$FF,$14,$4C,$FF,$10
    db $FF,$FF,$FF,$FF,$08,$A1,$64,$73
    db $FF,$FF,$FF,$FF,$97,$A1,$89,$1F
    db $FF,$FF,$FF,$03,$DB,$B0,$2C,$FF
    db $00,$4A,$5C,$F4,$FF,$FF,$FF,$00
FRAME_02H_MAP:
    db $00,$FF,$FF,$FF,$E3,$57,$45,$00
    db $FF,$FF,$FF,$FF,$11,$A1,$D8,$81
    db $FF,$FF,$FF,$FF,$FF,$BC,$CC,$40
    db $FF,$FF,$FF,$FF,$FF,$1D,$23,$FF
    db $FF,$FF,$FF,$FF,$FF,$FF,$06,$65
    db $37,$FF,$FF,$FF,$FF,$FF,$9E,$86
    db $FF,$FF,$FF,$FF,$FF,$02,$A1,$A8
    db $00,$E5,$5B,$45,$77,$32,$01,$00
FRAME_04H_MAP:
    db $00,$FF,$32,$33,$3A,$59,$E5,$00
    db $FF,$FF,$FF,$FF,$FF,$17,$D2,$9E
    db $46,$FF,$FF,$FF,$FF,$FF,$9A,$8B
    db $63,$FF,$FF,$FF,$FF,$FF,$19,$83
    db $F2,$FF,$FF,$FF,$FF,$FF,$FF,$78
    db $64,$24,$FF,$FF,$FF,$FF,$FF,$92
    db $FF,$45,$FF,$FF,$FF,$FF,$10,$32
    db $00,$E5,$5D,$45,$FF,$13,$63,$00
FRAME_06H_MAP:
    db $00,$01,$FE,$C0,$F7,$D4,$81,$00
    db $DB,$7C,$FF,$FF,$FF,$17,$E2,$A8
    db $3D,$FF,$FF,$FF,$FF,$FF,$FF,$8E
    db $96,$3F,$FF,$FF,$FF,$FF,$FF,$E0
    db $54,$8A,$FF,$FF,$FF,$FF,$FF,$17
    db $FF,$2F,$FF,$FF,$FF,$FF,$FF,$FF
    db $FF,$47,$35,$FF,$FF,$FF,$FF,$FF
    db $00,$E5,$5F,$22,$FF,$FF,$FF,$00
FRAME_08H_MAP:
    db $00,$01,$A1,$A1,$A1,$56,$FF,$00
    db $23,$E4,$B9,$7E,$70,$16,$1D,$40
    db $2C,$F5,$3B,$FF,$FF,$FF,$FF,$FF
    db $FF,$34,$EF,$45,$FF,$FF,$FF,$FF
    db $FF,$09,$52,$2A,$FF,$FF,$FF,$FF
    db $FF,$1C,$BB,$67,$FF,$FF,$FF,$FF
    db $FF,$47,$17,$27,$25,$FF,$FF,$FF
    db $00,$E5,$5F,$21,$FF,$FF,$FF,$00
FRAME_10H_MAP:
    db $00,$01,$50,$A1,$A8,$55,$81,$00
    db $73,$7D,$A2,$A1,$A1,$AF,$82,$3D
    db $81,$20,$FF,$AB,$30,$49,$FF,$FF
    db $62,$FF,$3C,$EC,$39,$FF,$FF,$FF
    db $FF,$FF,$FF,$17,$6C,$45,$FF,$FF
    db $FF,$FF,$10,$31,$A8,$41,$FF,$FF
    db $FF,$47,$FF,$1A,$AE,$FF,$FF,$FF
    db $00,$E5,$5F,$21,$12,$38,$FF,$00
FRAME_12H_MAP:
    db $00,$01,$EA,$9D,$A8,$9B,$4C,$00
    db $01,$B6,$B8,$CB,$A1,$A1,$A1,$FE
    db $A1,$C2,$FF,$98,$BA,$A1,$C7,$1F
    db $B5,$44,$FF,$15,$11,$C4,$6D,$FF
    db $F1,$2B,$FF,$FF,$6B,$5A,$42,$FF
    db $FF,$FF,$FF,$FF,$FF,$0D,$3E,$FF
    db $FF,$FF,$FF,$FF,$94,$CB,$68,$FF
    db $00,$E5,$5F,$4B,$FF,$7B,$FF,$00
FRAME_14H_MAP:
    db $00,$F5,$4D,$D9,$53,$57,$4C,$00
    db $10,$A1,$A1,$DC,$CD,$A1,$A1,$A8
    db $17,$A1,$A1,$FB,$BF,$CA,$A1,$87
    db $10,$A1,$AC,$2C,$FF,$B2,$BD,$85
    db $18,$A3,$ED,$FF,$FF,$FF,$93,$26
    db $FF,$2E,$15,$FF,$FF,$FF,$72,$61
    db $FF,$FF,$FF,$FF,$FF,$0F,$4E,$5B
    db $00,$E5,$5F,$4B,$FF,$17,$81,$00
FRAME_16H_MAP:
    db $00,$FF,$FF,$0C,$D7,$58,$0D,$00
    db $FF,$0F,$4F,$A9,$FA,$D0,$CA,$A8
    db $86,$18,$A1,$A1,$A6,$D1,$A1,$A1
    db $80,$FF,$95,$A1,$A1,$C6,$E1,$A1
    db $28,$FF,$04,$A1,$C3,$FF,$18,$75
    db $FF,$FF,$99,$C3,$90,$FF,$FF,$36
    db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
    db $00,$4A,$5D,$4B,$FF,$FF,$FF,$00
FRAME_18H_MAP:
    db $00,$14,$71,$F0,$33,$0E,$45,$00
    db $0F,$FF,$FF,$FF,$0B,$F8,$A9,$A8
    db $E6,$66,$FF,$E7,$A1,$A7,$F9,$8C
    db $CA,$88,$FF,$1E,$CB,$A1,$DE,$C8
    db $B4,$2C,$FF,$FF,$97,$A1,$A5,$74
    db $79,$FF,$FF,$FF,$DD,$A4,$29,$FF
    db $85,$FF,$FF,$FF,$B1,$76,$2C,$FF
    db $00,$4A,$5B,$21,$FF,$FF,$FF,$00
FRAME_20H_MAP:
    db $00,$01,$51,$DA,$FD,$60,$FF,$00
    db $FF,$7A,$6E,$FF,$FF,$FF,$EB,$A8
    db $FF,$E9,$D6,$FF,$FF,$03,$CE,$8D
    db $FF,$A1,$A6,$43,$FF,$9C,$A1,$DF
    db $FF,$CA,$A1,$69,$FF,$1B,$CA,$CF
    db $FF,$C1,$2C,$FF,$FF,$FF,$A0,$84
    db $FF,$6F,$FF,$FF,$FF,$07,$C5,$D5
    db $00,$C9,$9B,$22,$FF,$16,$FF,$00
FRAME_22H_MAP:
    db $00,$FF,$0A,$A1,$FC,$EE,$41,$00
    db $FF,$FF,$B3,$BE,$AA,$6A,$FF,$C1
    db $FF,$FF,$D3,$48,$FF,$FF,$FF,$8F
    db $FF,$FF,$05,$9F,$D6,$FF,$10,$B7
    db $FF,$FF,$95,$A1,$A6,$44,$18,$A1
    db $FF,$FF,$E8,$A1,$AD,$2C,$FF,$91
    db $FF,$FF,$F6,$2D,$FF,$FF,$03,$B8
    db $00,$4A,$5E,$22,$FF,$FF,$9E,$00

EarthDrawFrame:
    ld b,8
    ld c,8
    ld d,8
    ld e,12
    push ix
    push iy
    call PUT_FRAME
    pop iy
    pop ix
    ret
