; -----------------------------------------------------------------------------
; ALEXIS Mode 2 bitmap geometry scratch-area EQU map
; All aliases into AMY_BUFFER32 ($7000). No executable code.
; -----------------------------------------------------------------------------

AMY_MODE2_GEOMETRY_SCRATCH:
AMY_MODE2_X1        EQU AMY_BUFFER32+0
AMY_MODE2_Y1        EQU AMY_BUFFER32+1
AMY_MODE2_X2        EQU AMY_BUFFER32+2
AMY_MODE2_Y2        EQU AMY_BUFFER32+3
AMY_MODE2_SX        EQU AMY_BUFFER32+4
AMY_MODE2_SY        EQU AMY_BUFFER32+5
AMY_MODE2_DX        EQU AMY_BUFFER32+6
AMY_MODE2_DY        EQU AMY_BUFFER32+7
AMY_MODE2_ERR       EQU AMY_BUFFER32+8
AMY_MODE2_TMP       EQU AMY_BUFFER32+10
AMY_MODE2_USECOLOR  EQU AMY_BUFFER32+12
AMY_MODE2_COLOR     EQU AMY_BUFFER32+13
AMY_MODE2_CENTERX   EQU AMY_BUFFER32+14
AMY_MODE2_CENTERY   EQU AMY_BUFFER32+15
AMY_MODE2_RADIUS    EQU AMY_BUFFER32+16
AMY_MODE2_CIRCLEX   EQU AMY_BUFFER32+17
AMY_MODE2_CIRCLEY   EQU AMY_BUFFER32+18
