; Generated by tools/build-solar-system-encyclopedia.mjs.

SolarDrawFrame:
    ld l,a
    ld h,0
    add hl,hl
    add hl,hl
    add hl,hl
    add hl,hl
    add hl,hl
    add hl,hl
    ld de,AMY_UVAR_SolarFrames
    add hl,de
    ld b,8
    ld c,8
    ld d,8
    ld e,12
    push ix
    push iy
    call PUT_FRAME
    pop iy
    pop ix
    ret

SolarLoadFrames:
    dec a
    add a,a
    ld e,a
    ld d,0
    ld hl,SolarFrameAssetTable
    add hl,de
    ld e,(hl)
    inc hl
    ld h,(hl)
    ld l,e
    ld de,AMY_UVAR_SolarFrames
    jp SolarZx0ToRam

SolarUseNormalSprites:
    ld a,12
    ld (AMY_SPRITE_COUNT),a
    ld hl,SolarNormalSpriteAttributes
    ld de,AMY_SPRITE_TABLE
    ld bc,49
    ldir
    jp AMY_UPDATE_SPRITES

SolarUseSaturnSprites:
    ld a,16
    ld (AMY_SPRITE_COUNT),a
    ld hl,SolarSaturnSpriteAttributes
    ld de,AMY_SPRITE_TABLE
    ld bc,65
    ldir
    jp AMY_UPDATE_SPRITES

SolarZx0ToRam:
    ld bc,$FFFF
    push bc
    inc bc
    ld a,$80
SolarZx0Literals:
    call SolarZx0Elias
    ldir
    add a,a
    jr c,SolarZx0NewOffset
    call SolarZx0Elias
SolarZx0Copy:
    ex (sp),hl
    push hl
    add hl,de
    ldir
    pop hl
    ex (sp),hl
    add a,a
    jr nc,SolarZx0Literals
SolarZx0NewOffset:
    pop bc
    ld c,$FE
    call SolarZx0EliasLoop
    inc c
    ret z
    ld b,c
    ld c,(hl)
    inc hl
    rr b
    rr c
    push bc
    ld bc,1
    call nc,SolarZx0Backtrack
    inc bc
    jr SolarZx0Copy
SolarZx0Elias:
    inc c
SolarZx0EliasLoop:
    add a,a
    jr nz,SolarZx0EliasSkip
    ld a,(hl)
    inc hl
    rla
SolarZx0EliasSkip:
    ret c
SolarZx0Backtrack:
    add a,a
    rl c
    rl b
    jr SolarZx0EliasLoop

SolarFrameAssetTable:
    dw Asset_SolarSunFrames0,Asset_SolarSunFrames1,Asset_SolarMercuryFrames0,Asset_SolarMercuryFrames1,Asset_SolarVenusFrames0,Asset_SolarVenusFrames1,Asset_SolarEarthFrames0,Asset_SolarEarthFrames1,Asset_SolarMoonFrames0,Asset_SolarMoonFrames1,Asset_SolarMarsFrames0,Asset_SolarMarsFrames1,Asset_SolarJupiterFrames0,Asset_SolarJupiterFrames1,Asset_SolarSaturnFrames0,Asset_SolarSaturnFrames1,Asset_SolarUranusFrames0,Asset_SolarUranusFrames1,Asset_SolarNeptuneFrames0,Asset_SolarNeptuneFrames1,Asset_SolarPlutoFrames0,Asset_SolarPlutoFrames1

SolarNormalSpriteAttributes:
    db $3F,$60,$00,$01,$3F,$70,$04,$01,$4F,$60,$08,$01,$3F,$90,$0C,$01
    db $3F,$80,$10,$01,$4F,$90,$14,$01,$6F,$60,$18,$01,$6F,$70,$1C,$01
    db $5F,$60,$20,$01,$6F,$90,$24,$01,$6F,$80,$28,$01,$5F,$90,$2C,$01
    db $D0

SolarSaturnSpriteAttributes:
    db $3F,$60,$00,$01,$3F,$70,$04,$01,$4F,$60,$08,$01,$3F,$90,$0C,$01
    db $3F,$80,$10,$01,$4F,$90,$14,$01,$6F,$60,$18,$01,$6F,$70,$1C,$01
    db $5F,$60,$20,$01,$6F,$90,$24,$01,$6F,$80,$28,$01,$5F,$90,$2C,$01
    db $4F,$39,$30,$0F,$4F,$49,$34,$0F,$5F,$A9,$38,$0F,$5F,$B9,$3C,$0F
    db $D0
